env:
  browser: true
  es6: true
  amd: true
  node: true
  mocha: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
