env:
  browser: true
  es6: true
  amd: true
  node: true
  mocha: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
settings:
  react:
    pragma: "React"
    version: "detect"

